### ISSUE TITLE
Chat categories are not compatible with the bot

### ISSUE THREAD

**Issue by BladeofRagna** [xlash123/KHUx-Discord-Bot#22] opened 2017-09-25 03:14 UTC
This has only happened recently, but the bot is failing to respond. Lux notification isn't going off, and the bot can pull medal data. I'm sure this happened before, but I can't remember the solution to fix it.

Here's what happens when I attempt to use the bot.
https://gyazo.com/78ef8715e323c58a295209ed0bfa0bd4

**Comment by xlash123** [comment] 2017-09-25 03:38
Confirm that you are using the latest version 1.4.4 and the bot token you are using is valid.

**Comment by BladeofRagna** [comment] 2017-09-25 03:45
I can confirm I am using the latest version and the bot token is valid.

**Comment by xlash123** [comment] 2017-09-25 03:50
Have you restarted the bot? If so, do a few actions and copy the entire log.

**Comment by BladeofRagna** [comment] 2017-09-25 03:54
Yeah I've restarted countless times now.
https://gyazo.com/22ef0bf7f04d004daf85d70b04418f4e

This is all I can see that seems to be wrong

**Comment by xlash123** [comment] 2017-09-25 03:55
Link a pastebin of the entire log. I can't see why the issue is happening without the context.

**Comment by BladeofRagna** [comment] 2017-09-25 03:58
Ehh not entirely sure how to do that.. lol From what I can see without everything freaking out, the bot is connecting to the server, yet it says it isn't connected... it's so weird.

**Comment by xlash123** [comment] 2017-09-25 03:59
In the bot's console window:
Ctrl+A, Ctrl+C
Go to pastebin.com
Ctrl+V and create new paste
Link it here

**Comment by BladeofRagna** [comment] 2017-09-25 04:03
No idea why, but Ctrl+A doesn't do anything and Ctrl+C kills the bot entirely.

**Comment by xlash123** [comment] 2017-09-25 04:08
Oh right. Ctrl+C kills processes in cmd. Right-click on the title bar of command prompt, select Edit->Select All, then right click again, select Edit->Copy, then do the pastebin thing. I assume you are using Windows 10?

**Comment by BladeofRagna** [comment] 2017-09-25 04:09
Using windows 7 actually. lol

**Comment by BladeofRagna** [comment] 2017-09-25 04:10
https://pastebin.com/aWcDJLe3

Alright. Looking at this, alot of stuff gets cut off >.< So I don't know if anything here helps

**Comment by xlash123** [comment] 2017-09-25 04:14
Make a copy of your config folder, rename it, and delete the original. Put in the bot token when the bot asks for it, and see if that fixes the issue. This is unlike any error I've seen and I think it may have to do with corrupted config.

**Comment by BladeofRagna** [comment] 2017-09-25 04:19
Alright, did that and it didn't fix it. I even redownloaded the bot entirely as a fail-safe and that still didn't fix it. I'm gonna wait till tomorrow morning and see if the problem persists. And if it does, I'll let you know.

**Comment by xlash123** [comment] 2017-09-25 04:24
Try updating your Java version. 
Or you can use my host: https://www.reddit.com/r/KingdomHearts/comments/6q7ic8/khux_discord_bot_update_multiserver_support/?st=J7ZO5LFS&sh=f9bb2d06

**Comment by BladeofRagna** [comment] 2017-09-25 14:17
Restarted my computer, uninstalled, and reinstalled Java, and yet despite all that the problem is still persisting. I'll just have to use your host for now.

The one thing I have noticed which has happened consistently, is the whole "JSONObject["Type"] not a string" part. Maybe that has to do with the new discord update that added the chat categories.

**Comment by xlash123** [comment] 2017-09-25 14:20
Possibly. The issue could likely be fixed when the Discord API library I’m using gets updated.

**Comment by BladeofRagna** [comment] 2017-09-25 14:25
Gotcha. And I did just try to use your host. That's not working either LOL! So I guess the issue is discords new update

**Comment by bree-is-bree** [comment] 2017-09-25 14:29
Odd. I haven't had any bot issues in the latest Discord update, and I'm using the hosted version.

**Comment by BladeofRagna** [comment] 2017-09-25 14:41
Very odd. I'm gonna try and delete the channal cats. and see if that does anything.

**Comment by xlash123** [comment] 2017-09-25 14:53
Yeah. The issue seems to be with something between the Discord API and your server. The bot functions properly except for your server. I’ll still keep looking for a solution to this.

**Comment by BladeofRagna** [comment] 2017-09-25 18:05
OK! I can confirm now that the chat categories in the new discord update stops the bot from responding properly. Deleting them did the trick.

**Comment by xlash123** [comment] 2017-09-25 18:06
Thanks. I will update the description and let you know when it gets fixed.

**Comment by BladeofRagna** [comment] 2017-09-25 18:08
Cool!

**Comment by xlash123** [comment] 2017-09-26 01:08
Library update did the trick. Worked fine on testing server when I created a category.

Resolved in 1.4.5.

**Closed as completed by xlash123** 2017-09-26 01:08 UTC
