### ISSUE TITLE
Bot stopped running

### ISSUE THREAD

**Issue by KeybladeBrett** [xlash123/KHUx-Discord-Bot#21] opened 2017-08-31 20:48 UTC
The bot cannot run for whatever reason. I love it so much, but it just wont work anymore. It says Exception in thread "main". and closes

**Comment by xlash123** [comment] 2017-08-31 20:56
Make sure you are using the latest version of the bot. Then try running the bot with this command in command prompt:

java -jar "path to bot file" run

Use the quotes. Copy and paste what appears in the console.

**Comment by KeybladeBrett** [comment] 2017-08-31 20:59
Running bot version: 1.4.1
Initializing...
Got medal list
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.substring(Unknown Source)
        at xlash.bot.khux.MedalHandler.compileNicknames(MedalHandler.java:177)
        at xlash.bot.khux.MedalHandler.jpNicknames(MedalHandler.java:108)
        at xlash.bot.khux.MedalHandler.createNicknames(MedalHandler.java:97)
        at xlash.bot.khux.MedalHandler.<init>(MedalHandler.java:31)
        at xlash.bot.khux.KHUxBot.initialize(KHUxBot.java:122)
        at xlash.bot.khux.KHUxBot.<init>(KHUxBot.java:101)
        at xlash.bot.khux.KHUxBot.main(KHUxBot.java:96)

**Comment by xlash123** [comment] 2017-08-31 21:01
Ok. Thank you. I will look into this.

**Comment by KeybladeBrett** [comment] 2017-08-31 21:02
Yeah, no problem. What time does the lux occur, so I can send out the notification while the bot is down?

**Comment by xlash123** [comment] 2017-08-31 21:12
I have a hosted bot. You can invite it to your server using this link if you choose:

https://discordapp.com/login?redirect_to=%2Foauth2%2Fauthorize%3Fclient_id%3D300117950457708560%26scope%3Dbot%26permissions%3D0

**Comment by KeybladeBrett** [comment] 2017-08-31 21:31
ok thank you so much

**Comment by BladeofRagna** [comment] 2017-08-31 21:39
Having the same issue too. Glad it isn't something on my end.

**Comment by BladeofRagna** [comment] 2017-08-31 23:05
Tried out the bot you're hosting @xlash123 . Doesn't seem to work on my server for some reason. Can't get medal data, latest tweets and such. 🤔

**Comment by TehPower** [comment] 2017-08-31 23:10
Looks like this isn't isolated. My instance of the server is having the same issue with the same error that KHZYX is having.

**Comment by xlash123** [comment] 2017-08-31 23:16
I knew there was an issue withe the Tweets, so I wasn't alarmed due to that, but I've confirmed that my server was overloaded. I'm performing a restart, and the bot will be back online shortly. Thank you for bringing this to my attention. 

As for the main issue, I'll try to see what could be causing that issue. I don't spend as much time on the bot as before since I'm back in school now, so expect delay.

**Comment by KeybladeBrett** [comment] 2017-08-31 23:21
Ok, awesome. We can wait :)

**Comment by xlash123** [comment] 2017-08-31 23:58
Fixed in 1.4.2

**Closed as completed by xlash123** 2017-08-31 23:58 UTC
